name: Spellcheck

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".github/workflows/spellcheck.yml"

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check Markdown spelling
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: cspell.json
          files: "**/*.md"
